version: '3.7'

services:
  djangorless:
    container_name: djangorless
    image: 299264538740.dkr.ecr.us-east-1.amazonaws.com/djangorless
    command: python manage.py runserver 0:8000
    build:
      context: .
      cache_from:
        - 299264538740.dkr.ecr.us-east-1.amazonaws.com/djangorless
      args: 
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
        USE_S3: ${USE_S3}
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
      
  postgres:
    image: postgres:13.2-alpine
    container_name: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  pgdata: