version: '3.7'

services:
  djangorless:
    container_name: djangorless
    # image: 299264538740.dkr.ecr.us-east-1.amazonaws.com/djangorless
    command: python manage.py runserver 0:8000
    build:
      context: ./core
      # cache_from:
      #   - 299264538740.dkr.ecr.us-east-1.amazonaws.com/djangorless
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
        USE_S3: ${USE_S3}
        DATABASE_NAME: ${DATABASE_NAME}
        DATABASE_USER: ${DATABASE_USER}
        DATABASE_PASS: ${DATABASE_PASS}
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_PORT: ${DATABASE_PORT}
    volumes:
      - ./core:/app
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13.2-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
        - 5432:5432
    environment:
        POSTGRES_PASSWORD: ${DATABASE_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
