version: '3.7'

services:
  core: &core
    container_name: core
    image: 299264538740.dkr.ecr.us-west-1.amazonaws.com/djangorless:latest
    build:
      context: ./core
      # target: base
#      cache_from:
#        - 299264538740.dkr.ecr.us-west-1.amazonaws.com/djangorless:2
      args:
        ### Django
        USE_ADMIN: "True"
        ### AWS
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
        USE_S3: ${USE_S3}
        ### Database
        DATABASE_NAME: ${DATABASE_NAME}
        DATABASE_USER: ${DATABASE_USER}
        DATABASE_PASS: ${DATABASE_PASS}
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_PORT: ${DATABASE_PORT}
    volumes:
      - ./core:/app
#  admin:
#    <<: *core
#    container_name: admin
#    build:
#      context: ./core
#      args:
#        ### Django
#        USE_ADMIN: "True"
#
