version: '3.9'

services:
  core:
    stdin_open: true
    tty: true
    image: ${DJANGORLESS_CONTAINER_REPOSITORY_NAME}
#    depends_on:
#        selenium:
#            condition: service_healthy
    build:
      context: ./core
      args:
        ### AWS ###
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
        USE_S3: ${USE_S3}
        ### Cognito ###
        COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
        COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
        COGNITO_CLIENT_SECRET: ${COGNITO_CLIENT_SECRET}
    container_name: core
    ports:
      - 8000:8000
    volumes:
      - ./core:/home/core
    command: python manage.py runserver 0:8000

#  selenium:
#    image: selenium/standalone-chrome-debug:3.7.1
#    container_name: selenium
#    ports:
#      - 4444:4444
#      - 5900:5900
#    healthcheck:
#      # test: ["CMD-SHELL", "pg_isready -U postgres"]
#      # test: ["CMD-SHELL", "curl --fail http://localhost:4444/ || exit 1"]
#      test: ["CMD", "wget", "--spider", "http://localhost:4444"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#
