version: '3.9'

services:
  selenium:
    image: selenium/standalone-chrome-debug:3.7.1
    container_name: selenium
    ports:
      - 4444:4444
      - 5900:5900
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:4444"]
      interval: 10s
      timeout: 5s
      retries: 5

