org: nietzscheson
app: djangorless
service: djangorless

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  apiGateway:
    shouldStartNameWithService: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - s3:GetObject
       - s3:PutObject
      Resource: "arn:aws:s3:::*"


functions:
  app:
    image: 299264538740.dkr.ecr.us-east-1.amazonaws.com/djangorless:latest
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
      - schedule:
          rate: rate(5 minutes)
          input:
              warmer: true


resources:
    Resources:
        Assets:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: djangorless
                CorsConfiguration:
                    CorsRules:
                        -   AllowedHeaders: ["*"]
                            AllowedMethods: [GET]
                            AllowedOrigins: ["*"]
        AssetsBucketPolicy:
            Type: AWS::S3::BucketPolicy
            Properties:
                Bucket: !Ref Assets # References the bucket we defined above
                PolicyDocument:
                    Statement:
                        -   Effect: Allow
                            Principal: '*' # everyone
                            Action: 's3:GetObject' # to read
                            Resource: 'arn:aws:s3:::djangorless/*' # things in the bucket
