name: Build and Test on Pull Request

on: pull_request

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [14.x]
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
            USE_S3: True
            DJANGORLESS_CONTAINER_REPOSITORY_NAME: ${{ secrets.DJANGORLESS_CONTAINER_REPOSITORY_NAME }}
            SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        steps:
            - uses: actions/checkout@v2
            - name: Run Tests
              run: make test
